#!/bin/sh

goimports -w .
echo "包格式化完成"

go fmt ./...
echo "代码格式化完成"

s=$(git ls-files -m)

if [[ $s != "" ]];then
    echo "您的代码格式化有问题,请再次git add 一下"
    exit 1
fi

go vet ./...
echo "代码静态检查完成"

git add .

go test ./...

if [  $? == 2 ];then
    echo "您的代码存在一些问题,请修正错误然后再次提交"
    exit 1
fi

echo "代码测试完成"

golangci-lint run --disable-all -E errcheck  ./...

if [[ $? == 1 ]];then
    echo "您的代码存在一些问题,请修正错误然后再次提交"
    exit 1
fi

echo "您太棒了,您的代码very nice"
