[mongo]
address = "mongodb://user:pwd@ip/admin"
maxPoolSize = 200

[http]
listen = ":6126"

[mysql]
address = "root:123456@/aaa?charset=utf8&parseTime=True&loc=Local"
maxIdleConn = 10
maxOpenConn = 10

[redis]
address = "ip:port"
password = ""
maxPoolSize = 200 # 线程池大小



